#!/bin/sh

USER_AGENTS="
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15
Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
"

usage()
{
	echo "usage: search-youtube TEXT"
}

random_user_agent()
{
	printf "%s" "$USER_AGENTS" | shuf -n 1
}

http_get()
{
	wget -q -O - --header "User-Agent: $(random_user_agent)" "$@"
}

format()
{
	awk 'BEGIN {
	          FPAT = "([^ ]+)|(\"[^\"]+\")";
	     }
	     /"videoRenderer":/ {
	         videoRenderer = 1;
	     }
	     /"thumbnails":/ {
	         if (videoRenderer == 1) {
	             thumbnail = 1;
	         }
	     }
	     /"url":/ {
	         if (thumbnail == 1) {
	             gsub(/[",]/, "", $2); 
	             thumbnail = 0;
	         }
	     }
	     /"title":/ {
	         if (videoRenderer == 1) {
	             title = 1;
	         }
	     }
	     /"text":/ {
	         if (title == 1) {
	             gsub(/"/, "", $2);
	             print($2);
	             title = 0;
	         }
	     }
	     /"lengthText":/ {
	         if (videoRenderer == 1) {
	             lengthText = 1;
	         }
	     }
	     /"publishedTimeText":/ {
	         if (videoRenderer == 1) {
	             publishedTimeText = 1;
	         }
             }
	     /"simpleText":/ {
	         if (lengthText == 1) {
	             gsub(/"/, "", $2); 
	             print($2);
	             lengthText = 0;
	         }
	         else if (publishedTimeText == 1) {
	             gsub(/"/, "", $2); 
	             print($2);
	             publishedTimeText = 0;
	         }
	     }
	     /"watchEndpoint":/ {
	         if (videoRenderer == 1) {
	             watchEndpoint = 1;
	         }
	     }
	     /"videoId":/ {
	         if (watchEndpoint == 1) {
	             gsub(/[",]/, "", $2); 
	             print("https://youtube.com/watch?v=" $2);
	             watchEndpoint = 0;
	         }
	     }
	     /"ownerText":/ {
	         if (videoRenderer == 1) {
	             ownerText = 1;
	         }
	     }
	     /"text":/ {
	         if (ownerText == 1) {
	             gsub(/[",]/, "", $2); 
	             print($2 "\n");
	             ownerText = 0;
	             videoRenderer = 0;
	         }
	     }'
}

split()
{
	sed -e 's|{|{\n|g' -e 's|}|\n}|g' -e 's|":|": |g' -e 's|,|,\n|g'
}

scrape()
{
	sed -n -e 's|.*var ytInitialData = \({.*}\);</script>.*|\1|p'
}

query()
{
        http_get "https://www.youtube.com/results?search_query=$1"
}

main()
{
	if [ $# -ne 1 ]
	then
		usage
		exit 1
	fi

	query "$@" | scrape | split | format 
}

main "$@"
